# Generated by Django 4.2.5 on 2023-09-15 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="projects",
            new_name="Project",
        ),
    ]
